I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/park_scene.rpy", line 232, in script
    python:
  File "game/park_scene.rpy", line 233, in <module>
    exit()
NameError: name 'exit' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/park_scene.rpy", line 232, in script
    python:
  File "/home/collectionman/Descargas/renpy-7.4.1-sdk/renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/collectionman/Descargas/renpy-7.4.1-sdk/renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/park_scene.rpy", line 233, in <module>
    exit()
NameError: name 'exit' is not defined

Linux-5.4.0-64-generic-i686-with-debian-buster-sid
Ren'Py 7.4.1.1270
The Untold Path 0.5.1
Sun Jan 31 17:11:59 2021
